become_override: false
ocp_username: opentlc-mgr
silent: false

# OCP4 Authentication:
ocp4_workload_authentication_htpasswd_user_password: openshift
ocp4_workload_authentication_htpasswd_user_base: user
ocp4_workload_authentication_htpasswd_user_count: 1

# Shared Users
ocp4_workload_cloud_architecture_workshop_user_count: "{{ ocp4_workload_authentication_htpasswd_user_count }}"
ocp4_workload_cloud_architecture_workshop_user_prefix: "{{ ocp4_workload_authentication_htpasswd_user_base }}"

# ------------------------------------------------
# Workshop
# ------------------------------------------------

# Namespaces
ocp4_workload_cloud_architecture_workshop_namespace_prefix: globex

ocp4_workload_cloud_architecture_workshop_globex_user_password: openshift

# ------------------------------------------------
# Camel module common
# ------------------------------------------------

ocp4_workload_cloud_architecture_workshop_camel_common_application_namespace: openshift-gitops
ocp4_workload_cloud_architecture_workshop_camel_common_application_name: camel-common
ocp4_workload_cloud_architecture_workshop_camel_common_namespace: camel-common
ocp4_workload_cloud_architecture_workshop_camel_common_gitops_repo: https://github.com/btison/cloud-architecture-workshop-helm.git
ocp4_workload_cloud_architecture_workshop_camel_common_gitops_repo_tag: camel-common
ocp4_workload_cloud_architecture_workshop_camel_common_gitops_repo_path: globex-camel-common

ocp4_workload_cloud_architecture_workshop_camel_common_integration_replicas: 0
ocp4_workload_cloud_architecture_workshop_camel_common_integration_slack_app_id: "<slack app id>"
ocp4_workload_cloud_architecture_workshop_camel_common_integration_slack_token_app: "<slack token app>"
ocp4_workload_cloud_architecture_workshop_camel_common_integration_slack_token_bot: "<slack token bot>"

# ------------------------------------------------
# Workshop Bookbag
# ------------------------------------------------

ocp4_workload_cloud_architecture_workshop_bookbag: true
ocp4_workload_cloud_architecture_workshop_bookbag_application_name: bookbag
ocp4_workload_cloud_architecture_workshop_bookbag_namespace_prefix: bookbag

ocp4_workload_cloud_architecture_workshop_bookbag_applicationset_name: bookbag
ocp4_workload_cloud_architecture_workshop_bookbag_applicationset_namespace: openshift-gitops
ocp4_workload_cloud_architecture_workshop_bookbag_application_repo: >-
  https://github.com/rh-cloud-architecture-workshop/bookbag-helm.git
ocp4_workload_cloud_architecture_workshop_bookbag_application_repo_tag: main
ocp4_workload_cloud_architecture_workshop_bookbag_application_repo_path: bookbag

ocp4_workload_cloud_architecture_workshop_bookbag_var_azure_ocp_console: "<azure ocp console>"
ocp4_workload_cloud_architecture_workshop_bookbag_var_azure_ocp_api: "<azure ocp api>"

ocp4_workload_cloud_architecture_workshop_bookbag_var_ocp_api_internal: "https://172.30.0.1:443"

# ------------------------------------------------
# Camel Secrets
# ------------------------------------------------

ocp4_workload_cloud_architecture_workshop_camel_namespace_prefix: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-camel"

ocp4_workload_cloud_architecture_workshop_camel_discord_secret_name: discord-credentials
ocp4_workload_cloud_architecture_workshop_camel_discord_token: <discord token placeholder>
ocp4_workload_cloud_architecture_workshop_camel_discord_guild_id: <discord guild id placeholder>
ocp4_workload_cloud_architecture_workshop_camel_discord_guild_group: <discord guild group placeholder>

ocp4_workload_cloud_architecture_workshop_camel_minio_secret_name: client-s3
ocp4_workload_cloud_architecture_workshop_camel_minio_access_key: minio
ocp4_workload_cloud_architecture_workshop_camel_minio_secret_key: minio123
ocp4_workload_cloud_architecture_workshop_camel_minio_url_prefix: "minio-{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-camel"
ocp4_workload_cloud_architecture_workshop_camel_minio_token: "<minio token>"
