---

- name: Run rhsi cli commands (1)
  ansible.builtin.command:
    argv:
      - skupper
      - init
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_module_cdc_namespace_prefix }}-user1"
      - --enable-console
      - --enable-flow-collector
      - --console-auth
      - unsecured

- name: Run rhsi cli commands (2)
  ansible.builtin.command:
    argv:
      - skupper
      - token
      - create
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_module_cdc_namespace_prefix }}-user1"
      - /tmp/skupper.token

- name: Run rhsi cli commands (3)
  ansible.builtin.command:
    argv:
      - skupper
      - service
      - create
      - -n
      - "{{ ocp4_workload_cloud_architecture_workshop_module_cdc_namespace_prefix }}-user1"
      - globex-db
      - 5432
