---

- name: "Create namespaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_namespaces:
      - name: "{{ ocp4_workload_cloud_architecture_workshop_module_cdc_namespace_prefix }}-user"
        managedByArgo: ""
  retries: 10
  delay: 30

- name: "Give users access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rolebinding.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_bindings:
      - namespace: "{{ ocp4_workload_cloud_architecture_workshop_module_cdc_namespace_prefix }}-user"
        role: "admin"
  retries: 10
  delay: 30

- name: Wait for Kafka Podset to be ready
  kubernetes.core.k8s_info:
    api_version: core.strimzi.io/v1beta2
    kind: StrimziPodSet
    name: "kafka-kafka"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-user1"
  register: r_strimzi_podset
  retries: 120
  delay: 10
  until:
    - r_strimzi_podset.resources | length > 0
    - r_strimzi_podset.resources[0].status is defined
    - r_strimzi_podset.resources[0].status.readyPods is defined
    - r_strimzi_podset.resources[0].status.pods is defined
    - r_strimzi_podset.resources[0].status.pods == r_strimzi_podset.resources[0].status.readyPods

- name: Deploy ArgoCD application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'globex-cdc-application.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_module_cdc_namespace: "{{ ocp4_workload_cloud_architecture_workshop_module_cdc_namespace_prefix }}-user"
