---

- name: Remove dev spaces for users
  kubernetes.core.k8s:
    state: absent
    api_version: workspace.devfile.io/v1alpha2
    kind: DevWorkspace
    name: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_devworkspace_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_user_namespace_prefix }}-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user

- name: Remove dev spaces template for users
  kubernetes.core.k8s:
    state: absent
    api_version: workspace.devfile.io/v1alpha2
    kind: DevWorkspaceTemplate
    name: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_template_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_user_namespace_prefix }}-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user

- name: Remove dev spaces checluster
  kubernetes.core.k8s:
    state: absent
    api_version: org.eclipse.che/v2
    kind: CheCluster
    name: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_namespace }}"
    wait: true
