---

- name: Delete namespace for apicurio operator
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_apicurio_operator_namespace }}"
    wait: true

- name: Delete namespace for rhbk operator
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_rhbk_operator_namespace }}"
    wait: true
