---

- name: Delete bookbag namespaces
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_bookbag_namespace_prefix }}-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user

- name: Delete workshop deployer namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_workshop_deployer_namespace }}"
    wait: true

- name: Delete globex namespaces
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user

- name: Delete globex-mw namespaces
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-mw-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user

- name: Delete Camel common namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_camel_common_namespace }}"
    wait: true

- name: Delete namespace for apicurio designer
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_apicurio_namespace }}"

- name: Delete devspaces namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_user_namespace_prefix }}-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user

- name: Delete checluster namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_devspaces_namespace }}"
    wait: true

- name: Delete namespace for 3scale
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    wait: true

- name: Delete namespace for knative eventing
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_serverless_eventing_namespace }}"
    wait: true

- name: Delete namespace for knative serving
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_serverless_serving_namespace }}"
    wait: true

- name: Delete namespace for knative serving
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_serverless_serving_namespace }}-ingress"
    wait: true

- name: Delete argocd namespaces
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_argo_application_namespace_prefix }}-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user
