---

- name: Remove Camel common Application
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_cloud_architecture_workshop_camel_common_application_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_camel_common_application_namespace }}"
    wait: true
