---


- name: Delete cdc namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_module_cdc_namespace_prefix }}-user1"
    wait: true

- name: Delete mw namespace
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ ocp4_workload_cloud_architecture_workshop_namespace_prefix }}-user1"
    wait: true
