---

- name: Remove Globex application
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_cloud_architecture_workshop_globex_application_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_argo_application_namespace_prefix }}-{{ __user }}"
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user

- name: Remove Globex cluster-wide resources
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_cloud_architecture_workshop_globex_application_name }}-cluster-resources-{{ __user}}"
    namespace: openshift-gitops
    wait: true
  loop: "{{ r_cloud_architecture_workshop_users }}"
  loop_control:
    loop_var: __user
