---

- name: Remove Knative Kafka
  kubernetes.core.k8s:
    state: absent
    api_version: operator.serverless.openshift.io/v1alpha1
    kind: KnativeKafka
    name: "{{ ocp4_workload_cloud_architecture_workshop_serverless_knative_kafka_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_serverless_eventing_namespace }}"
    wait: true

- name: Remove Knative Eventing
  kubernetes.core.k8s:
    state: absent
    api_version: operator.knative.dev/v1beta1
    kind: KnativeEventing
    name: "{{ ocp4_workload_cloud_architecture_workshop_serverless_eventing_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_serverless_eventing_namespace }}"
    wait: true

- name: Remove Knative Serving
  kubernetes.core.k8s:
    state: absent
    api_version: operator.knative.dev/v1beta1
    kind: KnativeServing
    name: "{{ ocp4_workload_cloud_architecture_workshop_serverless_serving_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_serverless_serving_namespace }}"
    wait: true
