---

- name: Remove applicationset
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: ApplicationSet
    name: "{{ ocp4_workload_cloud_architecture_workshop_applicationset_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_applicationset_namespace }}"
    wait: true
