---

- name: Remove CDC Module
  ansible.builtin.include_tasks: remove_module_globex_cdc.yml

- name: Remove Globex application
  ansible.builtin.include_tasks: remove_workshop.yml

- name: Remove Namespaces
  ansible.builtin.include_tasks: remove_namespaces.yml
