---

- name: Running Pre Workload Tasks
  ansible.builtin.include_tasks:
    file: ./pre_workload.yml
    apply:
      become: "{{ become_override | bool }}"

- name: Remove Workshop Deployer
  ansible.builtin.include_tasks: remove_workshop_deployer.yml

- name: Remove Globex App
  ansible.builtin.include_tasks: remove_globex_app.yml

- name: Remove Camel common app
  ansible.builtin.include_tasks: remove_camel_common.yml

- name: Remove Apicurio Designer
  ansible.builtin.include_tasks: remove_apicurio_designer.yml

- name: Remove RHBK
  ansible.builtin.include_tasks: remove_rhbk.yml

- name: Remove Devspaces
  ansible.builtin.include_tasks: remove_devspaces.yml

- name: Remove 3scale
  ansible.builtin.include_tasks: remove_threescale.yml

- name: Remove serverless
  ansible.builtin.include_tasks: remove_serverless.yml

- name: Remove User ArgoCD instances
  ansible.builtin.include_tasks: remove_workshop.yml

- name: Remove Namespaces
  ansible.builtin.include_tasks: remove_namespaces.yml

- name: Remove Apicurio operator
  ansible.builtin.include_tasks: remove_apicurio_operator.yml

- name: Remove Service Registry operator
  ansible.builtin.include_tasks: remove_service_registry_operator.yml

- name: Remove Web Terminal operator
  ansible.builtin.include_tasks: remove_webterminal_operator.yml

- name: Remove AMQ Broker operator
  ansible.builtin.include_tasks: remove_amq_broker_operator.yml

- name: Remove Datagrid operator
  ansible.builtin.include_tasks: remove_datagrid_operator.yml

- name: Remove Red Hat Build of Keycloak Operator
  ansible.builtin.include_tasks: remove_rhbk_operator.yml

- name: Remove 3scale Operator
  ansible.builtin.include_tasks: remove_threescale_operator.yml

- name: Remove CamelK Operator
  ansible.builtin.include_tasks: remove_camelk_operator.yml

- name: Remove AMQ Streams Operator
  ansible.builtin.include_tasks: remove_amq_streams_operator.yml

- name: Remove Serverless Operator
  ansible.builtin.include_tasks: remove_serverless_operator.yml

- name: Remove OpenShift Gitops
  ansible.builtin.include_tasks: remove_openshift_gitops.yml

- name: Remove Pipelines Operator
  ansible.builtin.include_tasks: remove_openshift_pipelines_operator.yml

- name: Remove Namespaces Operators
  ansible.builtin.include_tasks: remove_namespaces_operators.yml
