---

- name: Remove argocd instance
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
    wait: true

- name: Remove clusterbinding
  kubernetes.core.k8s:
    state: absent
    api_version: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    name: gitops-cluster-admin
    wait: true

- name: Delete namespace for openshift gitops
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: openshift-gitops
    wait: true

- name: Remove OpenShift GitOps operator
  ansible.builtin.include_role:
    name: install_operator
  vars:
    install_operator_action: remove
    install_operator_name: "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_name }}"
    install_operator_namespace: "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_namespace }}"
    install_operator_channel: "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_channel }}"
    install_operator_catalog: "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_catalog }}"
    install_operator_automatic_install_plan_approval:
      "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_automatic_install_plan_approval | default(true) }}"
    install_operator_starting_csv: "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_starting_csv }}"
    install_operator_catalogsource_setup:
      "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_use_catalog_snapshot | default(false) }}"
    install_operator_catalogsource_name:
      "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_catalogsource_name | default('') }}"
    install_operator_catalogsource_namespace:
      "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_catalogsource_namespace | default('') }}"
    install_operator_catalogsource_image:
      "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_catalog_snapshot_image | default('') }}"
    install_operator_catalogsource_image_tag:
      "{{ ocp4_workload_cloud_architecture_workshop_openshift_gitops_operator_catalog_snapshot_image_tag | default('') }}"
