---

- name: Delete pipelinerun
  kubernetes.core.k8s:
    state: absent
    api_version: tekton.dev/v1
    kind: PipelineRun
    name: upload-cms-run-user1
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    wait: true

- name: Delete tenant
  kubernetes.core.k8s:
    state: absent
    api_version: capabilities.3scale.net/v1alpha1
    kind: Tenant
    name: user1
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    wait: true

- name: Delete APIManager
  kubernetes.core.k8s:
    state: absent
    api_version: apps.3scale.net/v1alpha1
    kind: APIManager
    name: apimanager
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    wait: true

- name: Undeploy ArgoCD application
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_cloud_architecture_workshop_threescale_apimanager_application_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_application_namespace }}"
    wait: true
