---

- name: Remove workshop deployer application
  kubernetes.core.k8s:
    state: absent
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: "{{ ocp4_workload_cloud_architecture_workshop_workshop_deployer_application_name }}"
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_workshop_deployer_application_namespace }}"
    wait: true
