---

- name: Deploy Keycloak CR
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_rhsso_namespace }}"
    definition: "{{ lookup('template', 'rhsso-keycloak.yaml.j2') }}"

- name: Deploy route for SSO
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_rhsso_namespace }}"
    definition: "{{ lookup('template', 'rhsso-route.yaml.j2') }}"

- name: Wait for sso to be ready
  kubernetes.core.k8s_info:
    api_version: apps/v1
    kind: statefulset
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_rhsso_namespace }}"
    label_selectors:
      - app = keycloak
  register: r_rhsso_statefulset
  retries: 60
  delay: 10
  changed_when: false
  until:
    - r_rhsso_statefulset.resources is defined
    - r_rhsso_statefulset.resources | length | int > 0
    - r_rhsso_statefulset.resources[0].status.readyReplicas is defined
    - r_rhsso_statefulset.resources[0].status.replicas is defined
    - r_rhsso_statefulset.resources[0].status.readyReplicas == r_rhsso_statefulset.resources[0].status.replicas
