---

# wait to APIManager resource creation
- name: Wait for 3scale pods to be ready
  kubernetes.core.k8s_info:
    api_version: apps.openshift.io/v1
    kind: DeploymentConfig
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    name: apicast-production
  register: r_threescale_apicast_production_dc
  until:
    - r_threescale_apicast_production_dc is defined
    - r_threescale_apicast_production_dc.resources is defined
    - r_threescale_apicast_production_dc.resources | list | length > 0
    - r_threescale_apicast_production_dc.resources[0].status is defined
    - r_threescale_apicast_production_dc.resources[0].status.readyReplicas is defined
    - r_threescale_apicast_production_dc.resources[0].status.readyReplicas | int >= 1
  retries: 60
  delay: 15

- name: Get the system seed secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: secret
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    name: system-seed
  register: r_threescale_system_seed_secret

- name: Get facts from system-seed secret
  ansible.builtin.set_fact:
    r_threescale_master_access_token: "{{ r_threescale_system_seed_secret.resources[0].data.MASTER_ACCESS_TOKEN | b64decode }}"
    r_threescale_master_password: "{{ r_threescale_system_seed_secret.resources[0].data.MASTER_PASSWORD | b64decode }}"
    r_threescale_admin_password: "{{ r_threescale_system_seed_secret.resources[0].data.ADMIN_PASSWORD | b64decode }}"
    r_threescale_master_domain: "{{ r_threescale_system_seed_secret.resources[0].data.MASTER_DOMAIN | b64decode }}"

- name: Set facts for tenant creation
  ansible.builtin.set_fact:
    r_threescale_system_master_url: "https://{{ r_threescale_master_domain }}.{{ r_openshift_subdomain }}"

- name: Wait until the master route is available
  kubernetes.core.k8s_info:
    api_version: route.openshift.io/v1
    kind: route
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    field_selectors:
      - "spec.host={{ r_threescale_master_domain }}.{{ r_openshift_subdomain }}"
  retries: 60
  delay: 15
  register: r_master_domain_route
  until:
    - r_master_domain_route is defined
    - r_master_domain_route.resources | list | length > 0

- name: "Create tenants for # of users: {{ ocp4_workload_cloud_architecture_workshop_threescale_tenant_user_count }}"
  ansible.builtin.include_tasks:
    file: threescale_tenant_loop.yml
  loop: "{{ range(1, ocp4_workload_cloud_architecture_workshop_threescale_tenant_user_count | int + 1, 1) | list }}"
  when:
    - ocp4_workload_cloud_architecture_workshop_threescale_tenant_user_count | int > 0
