---

# Name of ocp user that is an admin to the project where 3scale resources reside
- name: Set user ids
  ansible.builtin.set_fact:
    r_threescale_ocp_admin_id: "{{ ocp4_workload_cloud_architecture_workshop_threescale_ocp_user_prefix }}{{ item }}"
    r_threescale_tenant_admin_id: "{{ ocp4_workload_cloud_architecture_workshop_threescale_tenant_user_prefix }}{{ item }}"

- name: Set facts for tenants
  ansible.builtin.set_fact:
    r_threescale_org_name: "{{ r_threescale_ocp_admin_id }}-{{ ocp4_workload_cloud_architecture_workshop_threescale_tenant_org_name_base }}"
    r_threescale_tenant_admin_email:
      "{{ ocp4_workload_cloud_architecture_workshop_threescale_admin_email_user }}+\
      {{ r_threescale_ocp_admin_id }}@{{ ocp4_workload_cloud_architecture_workshop_threescale_admin_email_domain }}"

- name: Create the tenant CR for {{ r_threescale_org_name }}
  kubernetes.core.k8s:
    state: present
    namespace: "{{ ocp4_workload_cloud_architecture_workshop_threescale_namespace }}"
    merge_type:
      - strategic-merge
      - merge
    definition: "{{ lookup('template', resource) | from_yaml }}"
  loop:
    - "threescale-tenant-admin-secret.yaml.j2"
    - "threescale-tenant.yaml.j2"
  loop_control:
    loop_var: resource
