---

- name: Install AMQ Streams operator
  ansible.builtin.include_tasks: amq_streams_operator.yml

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml

- name: Install 3scale Operator
  ansible.builtin.include_tasks: threescale_operator.yml
