---

- name: Setup Bookbag
  when:
    - ocp4_workload_cloud_architecture_workshop_bookbag | bool
  ansible.builtin.include_tasks: bookbag.yml

- name: Deploy Camel secrets
  ansible.builtin.include_tasks: camel_secrets.yml

- name: Deploy Camel common application
  ansible.builtin.include_tasks: camel_common.yml

- name: Patch Service Registry operator
  ansible.builtin.include_tasks: service_registry_operator.yml
