---

- name: Setup cluster authentication
  when: ocp4_workload_authentication_idm_type == "htpasswd"
  ansible.builtin.include_tasks: setup_htpasswd.yml

- name: Install Dev Spaces operator
  ansible.builtin.include_tasks: devspaces_operator.yml

- name: Install Web Terminal operator
  ansible.builtin.include_tasks: webterminal_operator.yml

- name: Patch Web Terminal template
  ansible.builtin.include_tasks: webterminal_image.yml

- name: Install OpenShift Gitops
  ansible.builtin.include_tasks: openshift_gitops.yml

- name: Deploy workshop
  ansible.builtin.include_tasks: workshop.yml
