---
- name: "Create user namespaces"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_namespaces:
      - name: "{{ cloud_architecture_workshop_skupper_namespace_prefix }}-user"
  retries: 10
  delay: 30

- name: "Give users access to projects"
  kubernetes.core.k8s:
    state: present
    resource_definition: "{{ lookup('template', 'rolebinding.yaml.j2') }}"
  vars:
    r_cloud_architecture_workshop_bindings:
      - namespace: "{{ cloud_architecture_workshop_skupper_namespace_prefix }}-user"
        role: "admin"
  retries: 10
  delay: 30

- name: Deploy applicationset
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'applicationset.yaml.j2') | from_yaml }}"
