become_override: false
ocp_username: opentlc-mgr
silent: false

# Shared Users
ocp4_workload_cloud_architecture_workshop_user_count: 1
ocp4_workload_cloud_architecture_workshop_user_prefix: user

# ------------------------------------------------
# AMQ Streams Operator
# ------------------------------------------------

ocp4_workload_cloud_architecture_workshop_amq_streams_channel: ""
ocp4_workload_cloud_architecture_workshop_amq_streams_automatic_install_plan_approval: true
ocp4_workload_cloud_architecture_workshop_amq_streams_starting_csv: ""
ocp4_workload_cloud_architecture_workshop_amq_streams_wait_for_deploy: true
ocp4_workload_cloud_architecture_workshop_amq_streams_use_catalog_snapshot: false
ocp4_workload_cloud_architecture_workshop_amq_streams_catalogsource_name: redhat-operators-snapshot-amq-streams
ocp4_workload_cloud_architecture_workshop_amq_streams_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_cloud_architecture_workshop_amq_streams_catalog_snapshot_image_tag: "v4.6_2021_05_10"

# ------------------------------------------------
# OpenShift Gitops
# ------------------------------------------------

ocp4_workload_cloud_architecture_workshop_openshift_gitops_channel: stable
ocp4_workload_cloud_architecture_workshop_openshift_gitops_automatic_install_plan_approval: true
ocp4_workload_cloud_architecture_workshop_openshift_gitops_starting_csv: ""
ocp4_workload_cloud_architecture_workshop_openshift_gitops_pipelines_csv_prefix: openshift-pipelines-operator-rh

ocp4_workload_cloud_architecture_workshop_openshift_gitops_setup_cluster_admin: true

ocp4_workload_cloud_architecture_workshop_openshift_gitops_update_route_tls: false

ocp4_workload_cloud_architecture_workshop_openshift_gitops_update_resources: false

# ApplicationSet Controller
ocp4_workload_cloud_architecture_workshop_openshift_gitops_applicationset_controller_update: false
ocp4_workload_cloud_architecture_workshop_openshift_gitops_applicationset_controller_requests_cpu: 250m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_applicationset_controller_requests_memory: 512Mi
ocp4_workload_cloud_architecture_workshop_openshift_gitops_applicationset_controller_limits_cpu: "2"
ocp4_workload_cloud_architecture_workshop_openshift_gitops_applicationset_controller_limits_memory: 1Gi

# Application Controller
ocp4_workload_cloud_architecture_workshop_openshift_gitops_controller_update: false
ocp4_workload_cloud_architecture_workshop_openshift_gitops_controller_requests_cpu: 250m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_controller_requests_memory: 1Gi
ocp4_workload_cloud_architecture_workshop_openshift_gitops_controller_limits_cpu: "2"
ocp4_workload_cloud_architecture_workshop_openshift_gitops_controller_limits_memory: 2Gi
# Setting a default value for reconcile timeout as it needs to be configurable
# Reduce this value if you want to sync more frequently
ocp4_workload_cloud_architecture_workshop_openshift_gitops_controller_app_sync: 3m

# Redis
ocp4_workload_cloud_architecture_workshop_openshift_gitops_redis_update: false
ocp4_workload_cloud_architecture_workshop_openshift_gitops_redis_requests_cpu: 250m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_redis_requests_memory: 128Mi
ocp4_workload_cloud_architecture_workshop_openshift_gitops_redis_limits_cpu: 500m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_redis_limits_memory: 256Mi

# Repo Server
ocp4_workload_cloud_architecture_workshop_openshift_gitops_repo_update: false
ocp4_workload_cloud_architecture_workshop_openshift_gitops_repo_requests_cpu: 250m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_repo_requests_memory: 256Mi
ocp4_workload_cloud_architecture_workshop_openshift_gitops_repo_limits_cpu: "1"
ocp4_workload_cloud_architecture_workshop_openshift_gitops_repo_limits_memory: 1Gi

# DEX
ocp4_workload_cloud_architecture_workshop_openshift_gitops_dex_update: false
ocp4_workload_cloud_architecture_workshop_openshift_gitops_dex_requests_cpu: 125m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_dex_requests_memory: 128Mi
ocp4_workload_cloud_architecture_workshop_openshift_gitops_dex_limits_cpu: 500m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_dex_limits_memory: 256Mi

# Server
ocp4_workload_cloud_architecture_workshop_openshift_gitops_server_update: false
ocp4_workload_cloud_architecture_workshop_openshift_gitops_server_requests_cpu: 250m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_server_requests_memory: 128Mi
ocp4_workload_cloud_architecture_workshop_openshift_gitops_server_limits_cpu: 500m
ocp4_workload_cloud_architecture_workshop_openshift_gitops_server_limits_memory: 256Mi

ocp4_workload_cloud_architecture_workshop_openshift_gitops_resource_customizations: ""
# e.g.
# openshift_gitops_resource_customizations: |
  # argoproj.io/Application:
  #   health.lua: |
  #     hs = {}
  #     hs.status = "Progressing"
  #     hs.message = ""
  #     if obj.status ~= nil then
  #       if obj.status.health ~= nil then
  #         hs.status = obj.status.health.status
  #         hs.message = obj.status.health.message
  #       end
  #     end
  #     return hs
# --------------------------------
# Operator Catalog Snapshot Settings
# --------------------------------
# See https://github.com/redhat-cop/agnosticd/blob/development/docs/Operator_Catalog_Snapshots.adoc
# for instructions on how to set up catalog snapshot images

ocp4_workload_cloud_architecture_workshop_openshift_gitops_use_catalog_snapshot: false
ocp4_workload_cloud_architecture_workshop_openshift_gitops_catalogsource_name: redhat-operators-snapshot-gitops
ocp4_workload_cloud_architecture_workshop_openshift_gitops_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_cloud_architecture_workshop_openshift_gitops_catalog_snapshot_image_tag: v4.10_2022_07_18

# ------------------------------------------------
# Threescale Operator
# ------------------------------------------------

ocp4_workload_cloud_architecture_workshop_threescale_operator_channel: "threescale-2.13"
ocp4_workload_cloud_architecture_workshop_threescale_operator_automatic_install_plan_approval: true
ocp4_workload_cloud_architecture_workshop_threescale_operator_starting_csv: ""
ocp4_workload_cloud_architecture_workshop_threescale_operator_wait_for_deploy: true
ocp4_workload_cloud_architecture_workshop_threescale_operator_use_catalog_snapshot: false
ocp4_workload_cloud_architecture_workshop_threescale_operator_catalogsource_name: redhat-operators-snapshot-amq-streams
ocp4_workload_cloud_architecture_workshop_threescale_operator_catalog_snapshot_image: quay.io/gpte-devops-automation/olm_snapshot_redhat_catalog
ocp4_workload_cloud_architecture_workshop_threescale_operator_catalog_snapshot_image_tag: "v4.6_2021_05_10"
