---

- name: Install Workshop
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true

  tasks:
    - name: "Install Workshop"
      ansible.builtin.include_role:
        name: cloud_architecture_workshop_skupper
